-- Private operational data. Never commit rows or credentials to GitHub.
CREATE TABLE IF NOT EXISTS users (
 id TEXT PRIMARY KEY, username TEXT NOT NULL UNIQUE COLLATE NOCASE, name TEXT NOT NULL,
 role TEXT NOT NULL CHECK(role IN ('owner','admin')), pass_hash TEXT NOT NULL,
 enabled INTEGER NOT NULL DEFAULT 1, version INTEGER NOT NULL DEFAULT 1,
 must_change INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS inbox (
 id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL, company TEXT NOT NULL DEFAULT '',
 topic TEXT NOT NULL DEFAULT '', budget TEXT NOT NULL DEFAULT '', package TEXT NOT NULL DEFAULT '',
 message TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'baru', assignee TEXT NOT NULL DEFAULT '',
 note TEXT NOT NULL DEFAULT '', notification TEXT NOT NULL DEFAULT 'pending',
 version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS audit (
 id INTEGER PRIMARY KEY AUTOINCREMENT, actor TEXT NOT NULL, action TEXT NOT NULL,
 subject TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS rate_limits (key TEXT PRIMARY KEY, n INTEGER NOT NULL, expires INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS inbox_created ON inbox(created_at DESC);
CREATE INDEX IF NOT EXISTS rate_expires ON rate_limits(expires);
