import React, { useEffect, useState } from 'react';
import { Btn, Alert, usePesan } from './UI.jsx';

export async function request(path, method='GET', body) {
  const r=await fetch(path,{method,headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});
  const d=await r.json().catch(()=>({}));
  if(!r.ok){ if(r.status===401)window.dispatchEvent(new Event('xy-sesi-habis')); throw new Error(d.error||`HTTP ${r.status}`); }
  return d;
}
function Frame({title,lead,children}){return <><header className="top"><div><h1>{title}</h1><div className="sub">{lead}</div></div></header><div className="body workspace">{children}</div></>;}
function Fault({error}){return error?<Alert tipe="err">{error}</Alert>:null;}
export function Account({mandatory=false,onLogout}) {
  const [old,setOld]=useState(''),[next,setNext]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function save(e){e.preventDefault();setError('');if(next!==confirm)return setError('Konfirmasi password tidak sama.');setBusy(true);try{await request('/api/auth/password','POST',{lama:old,baru:next});await onLogout();}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <Frame title={mandatory?'Amankan akun xyteam':'Akun & keamanan'} lead={mandatory?'Ganti password sementara untuk membuka dashboard.':'Perubahan password mencabut semua sesi akun ini.'}><form className="workcard narrow" onSubmit={save}><Fault error={error}/><label>Password saat ini<input className="inp" type="password" autoComplete="current-password" value={old} onChange={e=>setOld(e.target.value)} required/></label><label>Password baru<input className="inp" type="password" minLength={12} autoComplete="new-password" value={next} onChange={e=>setNext(e.target.value)} required/></label><label>Ulangi password baru<input className="inp" type="password" minLength={12} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label><p className="hint">Minimal 12 karakter, maksimal 72 byte. Gunakan password unik dari password manager.</p><Btn type="submit" jenis="p" muat={busy}>Simpan & login ulang</Btn><button className="btn btn-g" type="button" onClick={onLogout}>Keluar</button></form></Frame>;
}
export function Team(){
 const [users,setUsers]=useState([]),[error,setError]=useState(''),[name,setName]=useState(''),[username,setUsername]=useState(''),[secret,setSecret]=useState(null),[busy,setBusy]=useState(false);
 const load=()=>request('/api/team').then(d=>setUsers(d.users)).catch(e=>setError(e.message));useEffect(()=>{load();},[]);
 async function act(fn){setBusy(true);setError('');setSecret(null);try{await fn();await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <Frame title="xyteam" lead="Akun individual untuk operasional. Hanya owner dapat mengelola anggota."><Fault error={error}/><div className="workcard"><h2>Tambah admin operasional</h2><p className="hint">Bisa mengelola konten, media, pesan dan pesanan. Tidak bisa mengubah owner, anggota, pengaturan situs, atau kunci API.</p><form className="workrow" onSubmit={e=>{e.preventDefault();act(async()=>{const d=await request('/api/team','POST',{nama:name,pengguna:username});setSecret({username,password:d.password});setName('');setUsername('');});}}><label>Nama anggota<input className="inp" value={name} onChange={e=>setName(e.target.value)} maxLength={100} required/></label><label>Username<input className="inp" value={username} onChange={e=>setUsername(e.target.value.toLowerCase())} pattern="[a-z0-9][a-z0-9_.\-]{2,39}" required autoComplete="off"/></label><Btn type="submit" jenis="p" muat={busy}>Buat akun</Btn></form></div>
 {secret&&<div className="workcard secret-once"><h2>Password sementara — salin sekarang</h2><p>Username: <strong>{secret.username}</strong></p><code>{secret.password}</code><p>Kirim secara pribadi. Anggota wajib mengganti password ini saat login. Tidak dikirim via email.</p><div className="workrow"><Btn onClick={()=>navigator.clipboard.writeText(`Username: ${secret.username}\nPassword sementara: ${secret.password}\nhttps://admin.xyverse.my.id`).catch(()=>setError('Salin manual dari kotak di atas.'))}>Salin kredensial</Btn><Btn onClick={()=>setSecret(null)}>Sudah disalin, sembunyikan</Btn></div></div>}
 <div className="workcard table-scroll"><table className="worktable"><thead><tr><th>Anggota</th><th>Peran</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.nama}</strong><small>@{u.pengguna}</small></td><td>{u.peran==='owner'?'Owner':'Admin operasional'}</td><td>{u.aktif?'Aktif':'Nonaktif'}{u.wajibGanti&&<small>Wajib ganti password</small>}</td><td>{u.peran!=='owner'&&<div className="workrow"><Btn disabled={busy} onClick={()=>{if(confirm(`${u.aktif?'Nonaktifkan':'Aktifkan'} ${u.pengguna}? Sesi lama akan dicabut.`))act(()=>request(`/api/team/${u.id}`,'PATCH',{aktif:!u.aktif}));}}>{u.aktif?'Nonaktifkan':'Aktifkan'}</Btn><Btn disabled={busy} onClick={()=>{if(confirm(`Reset password ${u.pengguna} dan cabut sesinya?`))act(async()=>{const d=await request(`/api/team/${u.id}`,'PATCH',{reset:true});setSecret({username:u.pengguna,password:d.password});});}}>Reset password</Btn></div>}</td></tr>)}</tbody></table>{!users.length&&<p>Belum ada data anggota yang dimuat.</p>}</div></Frame>;
}
export function Inbox(){
 const [data,setData]=useState(null),[offset,setOffset]=useState(0),[error,setError]=useState(''),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false);const say=usePesan();
 const load=()=>request(`/api/inbox?offset=${offset}`).then(setData).catch(e=>setError(e.message));useEffect(()=>{load();},[offset]);
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await request(`/api/inbox/${selected.id}`,'PATCH',selected);setSelected(null);await load();say('Status operasional tersimpan');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <Frame title="Pesan & pesanan" lead="Permintaan dari situs tersimpan di database privat. Ini bukan checkout atau bukti pembayaran."><Fault error={error}/><div className="workrow"><span>{data?.total||0} permintaan</span><Btn onClick={load}>Segarkan</Btn></div>
 {selected?<form className="workcard" onSubmit={save}><div className="workrow"><h2>{selected.name}</h2><button type="button" className="btn btn-g" onClick={()=>setSelected(null)}>Tutup detail</button></div><a href={`mailto:${encodeURIComponent(selected.email)}?subject=${encodeURIComponent('Re: '+(selected.topic||'Permintaan Xyverse'))}`}>{selected.email}</a><p>{selected.company} · {selected.package||selected.topic||'Umum'} · {selected.budget||'Anggaran belum diisi'}</p><p className="message-body">{selected.message}</p><p className="hint">Notifikasi email: {selected.notification==='sent'?'Diterima layanan email':selected.notification==='failed'?'Gagal — pesan tetap tersimpan di sini':'Menunggu'} · ID: {selected.id}</p><div className="workrow"><label>Status<select className="inp" value={selected.status} onChange={e=>setSelected({...selected,status:e.target.value})}>{['baru','diproses','menunggu','selesai','spam'].map(s=><option key={s}>{s}</option>)}</select></label><label>Penanggung jawab<select className="inp" value={selected.assignee} onChange={e=>setSelected({...selected,assignee:e.target.value})}><option value="">Belum ditugaskan</option>{data?.team.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label></div><label>Catatan internal<textarea className="inp" rows={5} maxLength={5000} value={selected.note} onChange={e=>setSelected({...selected,note:e.target.value})}/></label><Btn type="submit" jenis="p" muat={busy}>Simpan tindak lanjut</Btn></form>:
 <div className="workcard table-scroll"><table className="worktable"><thead><tr><th>Pengirim</th><th>Kebutuhan</th><th>Status</th><th>Masuk</th></tr></thead><tbody>{data?.items.map(x=><tr key={x.id}><td><button className="text-link" onClick={()=>setSelected(x)}>{x.name}</button><small>{x.email}</small></td><td>{x.package||x.topic||'Umum'}</td><td><span className="pill">{x.status}</span></td><td>{x.created_at}</td></tr>)}</tbody></table>{!data?.items.length&&<p className="empty-work">Belum ada permintaan. Pesan baru dari form situs akan masuk di sini.</p>}</div>}
 <div className="workrow"><Btn disabled={!offset} onClick={()=>{setSelected(null);setOffset(Math.max(0,offset-50));}}>Sebelumnya</Btn><span>Halaman {offset/50+1}</span><Btn disabled={!data||offset+50>=data.total} onClick={()=>{setSelected(null);setOffset(offset+50);}}>Berikutnya</Btn></div></Frame>;
}
export function Settings(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState('');useEffect(()=>{request('/api/settings').then(setData).catch(e=>setError(e.message));},[]);
 const update=(key,value)=>setData(d=>({...d,settings:{...d.settings,[key]:value}}));
 async function save(e){e.preventDefault();setBusy(true);setError('');setSaved('');try{const d=await request('/api/settings','PUT',data);setSaved(`Tersimpan di GitHub (${d.commitSha?.slice(0,7)}). Tunggu status TAYANG di menu Deploy.`);setData(await request('/api/settings'));}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <Frame title="Pengaturan situs" lead="Data publik. Perubahan memicu build situs; kredensial layanan tidak ditampilkan di sini."><Fault error={error}/>{saved&&<Alert tipe="ok">{saved}</Alert>}{data&&<form onSubmit={save}><div className="workcard"><h2>Kontak publik</h2><div className="workrow"><label>Email<input type="email" className="inp" value={data.settings.email} onChange={e=>update('email',e.target.value)} required/></label><label>WhatsApp (kosong = disembunyikan)<input className="inp" placeholder="628…" value={data.settings.wa} onChange={e=>update('wa',e.target.value)}/></label></div><p className="hint">Alamat penerima notifikasi internal tetap diatur terpisah melalui environment server.</p></div><div className="workcard"><h2>Paket Cloud PC</h2><p className="hint">Harga tampilan, bukan penagihan otomatis. Jangan menjanjikan stok/aktivasi sebelum dikonfirmasi tim.</p>{data.settings.plans.map((p,i)=><div className="workrow" key={p.id}>{[['name','Nama paket'],['priceId','Harga ID'],['priceEn','Harga EN']].map(([k,label])=><label key={k}>{label}<input className="inp" required maxLength={k==='name'?60:30} value={p[k]} onChange={e=>update('plans',data.settings.plans.map((v,j)=>j===i?{...v,[k]:e.target.value}:v))}/></label>)}</div>)}</div><div className="workcard"><h2>Akun sosial terverifikasi</h2>{data.settings.socials.map((s,i)=><div className="workrow" key={i}><label>Nama<input className="inp" value={s.nama} onChange={e=>update('socials',data.settings.socials.map((v,j)=>j===i?{...v,nama:e.target.value}:v))}/></label><label>URL HTTPS<input className="inp" type="url" required value={s.url} onChange={e=>update('socials',data.settings.socials.map((v,j)=>j===i?{...v,url:e.target.value}:v))}/></label><label>Ikon<select className="inp" value={s.ikon} onChange={e=>update('socials',data.settings.socials.map((v,j)=>j===i?{...v,ikon:e.target.value}:v))}>{['github','instagram','x','youtube','discord','linkedin','tiktok','telegram'].map(k=><option key={k}>{k}</option>)}</select></label><button type="button" className="btn btn-g" onClick={()=>update('socials',data.settings.socials.filter((_,j)=>j!==i))}>Hapus</button></div>)}<Btn onClick={()=>update('socials',[...data.settings.socials,{nama:'',url:'https://',handle:'',ikon:'github'}])}>Tambah sosial</Btn></div><Btn jenis="p" type="submit" muat={busy}>Simpan & bangun situs</Btn></form>}</Frame>;
}
export function DeployLive(){
 const [data,setData]=useState(null),[error,setError]=useState('');
 const load=()=>request('/api/deploy').then(d=>{setData(d);setError('');}).catch(e=>setError(e.message));useEffect(()=>{load();const t=setInterval(load,30000);return()=>clearInterval(t);},[]);
 const labels={READY:'TAYANG',BUILDING:'SEDANG DIBANGUN',QUEUED:'ANTREAN',INITIALIZING:'MENYIAPKAN',ERROR:'GAGAL',CANCELED:'DIBATALKAN'};
 return <div className="workcard"><div className="workrow"><h2>Deploy Vercel — status nyata</h2><Btn onClick={load}>Segarkan</Btn></div><Fault error={error}/><p className="hint">Simpan konten membuat commit. Situs baru berubah setelah deploy commit tersebut berstatus READY. Jika build gagal, versi sebelumnya tetap tayang.</p>{data?.items.map(d=><div className="deploy-row" key={d.id}><span className={`pill ${d.status==='READY'?'ok':d.status==='ERROR'?'wr':''}`}>{labels[d.status]||d.status}</span><code>{d.commit?.slice(0,7)||'Redeploy'}</code><span>{d.message||'Pembaruan konfigurasi'}</span>{d.status==='READY'&&<a href={`https://${d.url}`} target="_blank" rel="noreferrer">Lihat versi ↗</a>}</div>)}</div>;
}
export function Audit(){const [items,setItems]=useState([]),[error,setError]=useState('');useEffect(()=>{request('/api/audit').then(d=>setItems(d.items)).catch(e=>setError(e.message));},[]);return <Frame title="Aktivitas tim" lead="100 aktivitas terbaru; tidak menyimpan password atau isi pesan."><Fault error={error}/><div className="workcard table-scroll"><table className="worktable"><thead><tr><th>Waktu</th><th>Akun</th><th>Tindakan</th><th>Objek</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.created_at}</td><td>{x.actor}</td><td>{x.action}</td><td>{x.subject}</td></tr>)}</tbody></table></div></Frame>;}
